
services:
  api:
    image: saurabhxkumarx/sonix-music-app:latest
    # container_name: api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - AWS_REGION=ap-south-1
    volumes:
     - /home/ubuntu/.aws:/home/node/.aws:ro
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    # container_name: redis_cache
    volumes:
      - redisdata:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  migrate:
    image: saurabhxkumarx/sonix-music-app:latest
    command: npx prisma migrate deploy
    env_file:
      - .env
    environment:
      - AWS_REGION=ap-south-1
    volumes:
      - /home/ubuntu/.aws:/home/node/.aws:ro
    networks:
      - app-network

volumes:
  redisdata:

networks:
  app-network:
    driver: bridge